/*
DROP TABLE user_history CASCADE CONSTRAINTS;
DROP TABLE playlist_songs CASCADE CONSTRAINTS;
DROP TABLE playlist_follows CASCADE CONSTRAINTS;
DROP TABLE playlists CASCADE CONSTRAINTS;
DROP TABLE user_liked_songs CASCADE CONSTRAINTS;
DROP TABLE user_following_artists CASCADE CONSTRAINTS;
DROP TABLE songs CASCADE CONSTRAINTS;
DROP TABLE albums CASCADE CONSTRAINTS;
DROP TABLE artist_profiles CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

DROP SEQUENCE HISTORY_SEQ;
DROP SEQUENCE PLAYLISTS_SEQ;
DROP SEQUENCE SONGS_SEQ;
DROP SEQUENCE ALBUMS_SEQ;
DROP SEQUENCE USERS_SEQ;

DROP TRIGGER trg_users_created_at;
DROP TRIGGER trg_songs_created_at;
*/

-- Initialize sequences
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SONGS_SEQ START WITH 1 INCREMENT BY 1;

-- Creating trigger for users table created_at timestamp
CREATE OR REPLACE TRIGGER trg_users_created_at
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
    IF :NEW.created_at IS NULL THEN
        :NEW.created_at := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- Creating trigger for songs table created_at timestamp
CREATE OR REPLACE TRIGGER trg_songs_created_at
BEFORE INSERT ON songs
FOR EACH ROW
BEGIN
    IF :NEW.created_at IS NULL THEN
        :NEW.created_at := CURRENT_TIMESTAMP;
    END IF;
END;
/
